# path to db 
#   jdbc:h2:mem:tacocloud
spring:     
    cassandra:
        keyspace-name: tacocloud
        schema-action: recreate
        local-datacenter: datacenter1
        # contact-points:
        # - localhost
        port: 9043